### PR TITLE
Add version 0.2.0

### PR DESCRIPTION
**Pull request by philip-khor**
A recipe I"m trying to add (conda-forge/staged-recipes#12154) requires this exact version of gql. 

Requesting if this can be merged to a separate branch or the master branch (see https://github.com/conda-forge/markdown-feedstock/pull/7#issuecomment-534589274)

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by philip-khor** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
we need to merge this to a separated branch
I will create one in a couple of minutes

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by philip-khor** [comment]
thanks!

**Pull request merged**
